# data args
data_dir: "markup_from_dump"
output_dir: "result"
model_name_or_path: "DeepPavlov/rubert-base-cased"
label_names: ["sentiment_label", "labels"]
# stages
do_train: true
do_eval: true
# training args
max_seq_len: 128
learning_rate: 5.0e-5
weight_decay: 0.1
dropout_rate: 0.1
num_train_epochs: 10
warmup_ratio: 0.1
per_device_train_batch_size: 16
evaluation_strategy: "epoch"
save_strategy: "epoch"
load_best_model_at_end: true
push_to_hub: false
